export const GET_MUSIC_RECORD_REQUEST = "GET_MUSIC_RECORD_REQUEST";
export const GET_MUSIC_RECORD_SUCESS = "GET_MUSIC_RECORD_SUCESS";
export const GET_MUSIC_RECORD_FAILUR = "GET_MUSIC_RECORD_FAILUR";
